guide/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('attractions', views.AttractionListView.as_view(), name='attractions'),
    path('attraction/<int:pk>',
         views.AttractionDetailView.as_view(), name='attraction-detail'),
    path('shoppingcart',
         views.ShoppingCartView.as_view(), name='shopping-cart'),
    path('addattractiontoshoppingcart/<int:pk>',
         views.addAttractionToShoppingCart, name='add-attraction-to-shopping-cart'),
    path('addattractiontotripplan/<int:trip_pk>/<int:attraction_pk>',
         views.addAttractionToTripPlan, name='add-attraction-to-trip-plan'),
    path('removeattractionfromplan/<int:trip_pk>/<int:attr_pk>',
         views.removeAttractionFromPlan, name='remove-attraction-from-plan'),
    path('removeattractionfromshoppingcart/<int:pk>',
         views.removeAttractionFromShoppingCart, name='remove-attraction-from-shopping-cart'),
    path('saveplan/<int:pk>',
         views.saveTripPlan, name='save-trip-plan'),
    path('tripplans', views.TripPlanListView.as_view(), name='trip-plans'),
    path('tripplan/<int:pk>', views.TripPlanDetailView.as_view(),
         name='trip-plan-detail'),
    path("mytripplans", views.MyTripPlanListView.as_view(), name="my-trip-plans"),
    path('signup', views.SignUp.as_view(), name='signup'),
    path('removemyplan/<int:pk>', views.removeMyPlan, name='remove-my-plan'),
    path('changename/<int:pk>',
         views.changeNameOfPlan, name='change-name'),
    path('myaccount/general', views.generalSettings, name='general'),
    path('myaccount/changepassword', views.change_password, name='change-password'),
    path('', views.home, name='home'),
    path('pdf/<int:pk>', views.html_to_pdf_view, name='pdf'),
]

guideproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('guide/', include('guide.urls')),  
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='guide/', permanent=True)),

]

guide/models.py
import math
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class Client(User):
    name = models.CharField(_("Name"), max_length=50,
                            null=True, blank=True, default="")
    surname = models.CharField(
        _("Surname"), max_length=50, null=True, blank=True, default="")

    def __str__(self):
        return ''+self.username+': '+self.name+' '+self.surname

    class Meta:
        verbose_name = "client"


class Category(models.Model):
    name = models.CharField(_("Name"), max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "categories"


class Attraction(models.Model):
    name = models.CharField(_("Name"),
                            max_length=200, help_text="Enter attraction's name.")
    description = models.TextField(max_length=500)
    categories = models.ManyToManyField(
        "Category")
    localization = models.ForeignKey(
        "Localization", verbose_name=_("Address"), on_delete=models.CASCADE, null=True, blank=True)
    timeNeededToSightsee = models.FloatField(
        _("Time neede to sightsee (in hours)"))
    ticketCost = models.FloatField(
        _("Ticket's cost"), default=0)

    def __str__(self):
        return self.name

    def display_category(self):
        """Create a string for the Category. This is required to display category in Admin."""
        return ', '.join(category.name for category in self.categories.all())

    def getTimeAsFormattedString(self):
        hours = int(self.timeNeededToSightsee)
        minutes = int((self.timeNeededToSightsee % 1)*60)
        result = ''
        if hours:
            result += str(hours) + ' godzin(-a/y) '
        if minutes:
            result += str(minutes) + ' minut(-a)'
        return result

    def getFormattedCost(self):
        if self.ticketCost == 0:
            return 'Darmowe'
        else:
            return f'{str(self.ticketCost)} zł'

    display_category.short_description = 'Category'

    class Meta:
        ordering = ['name']


class Localization(models.Model):
    street = models.CharField(
        _("Street"), max_length=100, null=True, blank=True, default='')
    zipCode = models.CharField(_("Zip code"), max_length=100)
    city = models.CharField(_("City"), max_length=100)
    lattitude = models.FloatField(_("Lattitude"), default=0)
    longitude = models.FloatField(_("Longitude"), default=0)

    def __str__(self):
        if self.street:
            return '' + str(self.street) + ', ' + self.zipCode + ', ' + self.city
        else:
            return '' + self.zipCode + ', ' + self.city


class ShoppingCart(models.Model):
    owner = models.ForeignKey("Client", verbose_name=_(
        "właściciel"), on_delete=models.CASCADE)
    attractions = models.ManyToManyField(
        "Attraction", verbose_name=_("Attraction list"), blank=True)

    def owner_username(self):
        return self.owner.username

    def owner_name(self):
        return self.owner.name

    def owner_surname(self):
        return self.owner.surname

    def getNumberOfAttractions(self):
        return len(attractions)

    def getTotalCost(self):
        tCost = 0
        for attraction in self.attractions.all():
            tCost += attraction.ticketCost
        return tCost

    def getTotalTime(self):
        tTime = 0
        for attraction in self.attractions.all():
            tTime += attraction.timeNeededToSightsee
        return tTime

    def getTimeAsFormattedString(self):
        time = self.getTotalTime()
        hours = int(time)
        minutes = int((time % 1)*60)
        result = ''
        if hours:
            result += str(hours) + ' godzin(-a/y) '
        if minutes:
            result += str(minutes) + ' minut(-a)'
        return result

    def getFormattedCost(self):
        totalTime = self.getTotalCost()
        if totalTime == 0:
            return 'Darmowe'
        else:
            return f'{totalTime} zł'


class TripPlan(models.Model):
    name = models.CharField(_("Name"), max_length=150)
    creator = models.ForeignKey("Client", verbose_name=_(
        "Creator"), on_delete=models.CASCADE, null=True, blank=True)
    attractions = models.ManyToManyField(
        "Attraction", verbose_name=_("Attraction list"))

    def __str__(self):
        return '' + self.name

    def getNumberOfAttractions(self):
        return len(self.attractions.all())

    def getTotalTime(self):
        totalTime = 0
        for attraction in self.attractions.all():
            totalTime += attraction.timeNeededToSightsee
        return totalTime

    def getTotalTimeSplit(self):
        totalTime = self.getTotalTime()
        return math.floor(totalTime), round((totalTime-math.floor(totalTime))*60)

    def getFormattedTime(self):
        time = self.getTotalTime()
        hours = int(time)
        minutes = int((time % 1)*60)
        result = ''
        if hours:
            result += str(hours) + ' godzin(-a/y) '
        if minutes:
            result += str(minutes) + ' minut(-a)'
        return result

    def getTotalCost(self):
        totalPrice = 0
        for attraction in self.attractions.all():
            totalPrice += attraction.ticketCost
        return totalPrice

    def getFormattedCost(self):
        totalTime = self.getTotalCost()
        if totalTime == 0:
            return 'Darmowe'
        else:
            return f'{totalTime} zł'

    class Meta:
        ordering = ['name']

guide/views.py
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse
from weasyprint import HTML
from django.template.loader import render_to_string
from django_filters.views import FilterView
from .filters import AttractionListFilter
from django.contrib.auth.decorators import login_required
from . import google_maps_api
import simplejson
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView, ListView, TemplateView
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.models import User
from .models import Attraction, TripPlan, Localization, Category, Client, ShoppingCart
from .forms import SaveTripPlanForm, SignUpForm, CustomUserChangeForm, ChangeTripPlanNameForm, CustomPasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages

from django.views.generic import FormView
from django.contrib.auth import authenticate, login

from django.contrib.auth.forms import UserChangeForm
import sys

from django.contrib.auth.mixins import LoginRequiredMixin


def home(request):
    return render(request, 'home.html', {'form': SignUpForm})


def extractInfo(attractionList):
    formattedInfo = []
    try:
        for attraction in attractionList:
            formattedInfo.append({'name': attraction.name,
                                  'lat-lng': {'lat': attraction.localization.lattitude, 'lng': attraction.localization.longitude}})
        return formattedInfo
    except:
        pass
    try:
        formattedInfo.append({'name': attractionList.name,
                              'lat-lng': {'lat': attractionList.localization.lattitude, 'lng': attractionList.localization.longitude}})
        return formattedInfo
    except:
        pass


class AttractionListView(FilterView):
    model = Attraction
    filterset_class = AttractionListFilter
    context_object_name = 'attractions'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = SignUpForm
        if self.request.user.is_authenticated:
            attractions = ShoppingCart.objects.get(
                owner=self.request.user).attractions.all()
            attractionPKs = attractions.values_list('pk')
            availableAttractions = Attraction.objects.exclude(
                pk__in=attractionPKs)
            context['availableAttractions'] = availableAttractions
        return context


class AttractionDetailView(DetailView):
    model = Attraction

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['attractionLocalization'] = extractInfo(self.object)
        context['form'] = SignUpForm
        if self.request.user.is_authenticated:
            shoppingcart = ShoppingCart.objects.get(owner=self.request.user)
            if shoppingcart.attractions.filter(pk=self.object.pk):
                context['inPlan'] = True
        return context


class TripPlanListView(ListView):
    model = TripPlan

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = SignUpForm
        return context

    def get_queryset(self):
        return TripPlan.objects.filter(creator__isnull=True)


class TripPlanDetailView(DetailView):
    model = TripPlan

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        attractionLocalizations = extractInfo(self.object.attractions.all())
        context["attractionLocalizations"] = attractionLocalizations
        hours, minutes = self.object.getTotalTimeSplit()
        context['hours'] = hours
        context['minutes'] = minutes
        context['form'] = SignUpForm
        if self.request.user.is_authenticated and self.object.creator:
            if self.object.creator.pk == self.request.user.pk:
                availableAttractions = Attraction.objects.exclude(
                    pk__in=self.object.attractions.values_list('pk'))
                context['availableAttractions'] = availableAttractions
                context['changeNameForm'] = ChangeTripPlanNameForm
        return context


class MyTripPlanListView(LoginRequiredMixin, ListView):
    model = TripPlan
    template_name = "guide/mytripplan_list.html"
    context_object_name = "mytripplans"

    def get_queryset(self):
        return TripPlan.objects.filter(creator=self.request.user)


class ShoppingCartView(LoginRequiredMixin, TemplateView):
    template_name = 'guide/shoppingcart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        shoppingCart = ShoppingCart.objects.get(owner=self.request.user)
        attractions = shoppingCart.attractions.all()
        attractionPKs = attractions.values_list('pk')
        availableAttractions = Attraction.objects.exclude(pk__in=attractionPKs)
        context['shoppingcart'] = shoppingCart
        context['attractions'] = attractions
        context['saveform'] = SaveTripPlanForm
        context['availableattractions'] = availableAttractions
        attractionLocalizations = extractInfo(attractions)
        context["attractionLocalizations"] = attractionLocalizations
        return context


@login_required
def addAttractionToShoppingCart(request, pk):
    attractionInstance = get_object_or_404(Attraction, pk=pk)
    clientInstance = get_object_or_404(Client, pk=request.user.pk)
    shoppingCartInstance = get_object_or_404(
        ShoppingCart, owner=clientInstance)
    shoppingCartInstance.attractions.add(attractionInstance)
    return HttpResponseRedirect(reverse('attractions'))


@login_required
def addAttractionToTripPlan(request, trip_pk, attraction_pk):
    attractionInstance = get_object_or_404(Attraction, pk=attraction_pk)
    clientInstance = get_object_or_404(Client, pk=request.user.pk)
    tripPlanInstance = get_object_or_404(
        TripPlan, pk=trip_pk)
    tripPlanInstance.attractions.add(attractionInstance)
    return HttpResponseRedirect(reverse('trip-plan-detail', kwargs={'pk': trip_pk}))


@login_required
def removeAttractionFromShoppingCart(request, pk):
    attractionInstance = get_object_or_404(Attraction, pk=pk)
    clientInstance = get_object_or_404(Client, pk=request.user.pk)
    shoppingCartInstance = get_object_or_404(
        ShoppingCart, owner=clientInstance)
    shoppingCartInstance.attractions.remove(attractionInstance)
    return HttpResponseRedirect(reverse('shopping-cart'))


@login_required
def removeAttractionFromPlan(request, trip_pk, attr_pk):
    attractionInstance = get_object_or_404(Attraction, pk=attr_pk)
    tripplan = get_object_or_404(TripPlan, pk=trip_pk)
    tripplan.attractions.remove(attractionInstance)
    return HttpResponseRedirect(reverse('trip-plan-detail', kwargs={'pk': trip_pk}))


@login_required
def saveTripPlan(request, pk):
    if request.method == 'POST':
        form = SaveTripPlanForm(request.POST)
        if form.is_valid():
            tripplan = TripPlan.objects.create(creator=Client.objects.get(
                pk=request.user.pk), name=form.cleaned_data['name'])
            shoppingcart = ShoppingCart.objects.get(pk=pk)
            tripplan.attractions.set(shoppingcart.attractions.all())
            shoppingcart.attractions.clear()
            tripplan.save()

    return HttpResponseRedirect(reverse('my-trip-plans'))


class SignUp(FormView):
    form_class = SignUpForm
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        form.save()
        username = self.request.POST['username']
        password = self.request.POST['password1']
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return redirect(reverse('home'))


@login_required
def removeMyPlan(request, pk):
    tripPlan = get_object_or_404(TripPlan, pk=pk).delete()
    return HttpResponseRedirect(reverse('my-trip-plans'))


@login_required
def changeNameOfPlan(request, pk):
    if request.method == 'POST':
        form = ChangeTripPlanNameForm(request.POST)
        if form.is_valid():
            tripplan = TripPlan.objects.get(pk=pk)
            tripplan.name = form.cleaned_data['name']
            tripplan.save()

    return HttpResponseRedirect(reverse('trip-plan-detail', kwargs={'pk': pk}))


@login_required
def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(
                request, 'Your password was successfully updated!')
            return redirect('change-password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = CustomPasswordChangeForm(request.user)
    return render(request, 'registration/changepassword.html', {
        'form': form
    })


@login_required
def generalSettings(request):
    client = get_object_or_404(Client, pk=request.user.pk)
    if request.method == 'POST':
        form = CustomUserChangeForm(
            request.POST, instance=request.user, initial=None)
        if form.is_valid():
            cd = form.cleaned_data
            client.email = cd['email'] or ''
            client.name = cd['name'] or ''
            client.surname = cd['surname'] or ''
            client.save()
            messages.success(
                request, 'Your settings were successfully updated!')
            return redirect('general')
    else:
        form = CustomUserChangeForm(instance=request.user, initial={
            'name': client.name,
            'surname': client.surname
        })
    return render(request, "registration/general.html", {
        'form': form
    })


def html_to_pdf_view(request, pk):

guide/templates/guide/attraction_detail.html
{% extends "base.html" %}
{% block title %}
    {{attraction.name}} details
{% endblock title %}
{% block styles %}
<style>
#map{
    height:600px;
    width:800px;
    margin: 0 auto 30px auto;
}
.border-3{
    border-width:3px !important;
}
</style>
{% endblock styles %}
{% block content %}
{% load static %}
{% block signin_modal %}
        {% include "registration/signinmodal.html" with redirect='attraction-detail' pk=attraction.pk %}
    {% endblock signin_modal %}
    {% block signup_modal %}
        {% include "registration/signupmodal.html" with redirect='attraction-detail' pk=attraction.pk %}
    {% endblock signup_modal %}
<section class="container-fluid">
    <div class="row mt-4 mr-4">
        <div class="col-4 text-right">
        </div>
        <div class="col-4 text-center border-bottom border-primary border-3">
        <h4>{{attraction.name}}</h4>
        </div>
        <div class="col-4 text-right">
        {% if not inPlan and user.is_authenticated %}
            <a href="{% url 'add-attraction-to-shopping-cart' attraction.pk %}" class="icon-wrapper">
                    <i class="far fa-plus-square"></i>
            </a>
        {% endif %}
        </div>
    </div>

    <div class="row mt-32">
        <div class="col-6">
            <div class="row">
            <div class="col">
                        <h3 class="text-center">Lokalizacja na mapie</h3>
                    </div>
            </div>
            <div class="row">
            <div class="col">
            <div class="listing-block">
               <div class="card w-75  mx-auto">
                <img class="card-img-top" src="{% static "images/" %}{{attraction.name}}.jpeg" alt="{{attraction.name}}">
                <div class="card-header py-5">
                    <h3>{{attraction.name}}</h3>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                    <h4 class="pb-3">Opis</h4>
                        {{attraction.description}}
                    </li>
                    <li class="list-group-item">
                    <h4 class="pb-3">Lokalizacja</h4>
                        {{attraction.localization}}
                    </li>
                    <li class="list-group-item">
                    <h4 class="pb-3">Koszt</h4>
                        {{attraction.getFormattedCost}}
                    </li>
                    <li class="list-group-item">
                    <h4 class="pb-3">Potrzebny czas</h4>
                        {{attraction.getTimeAsFormattedString}}
                    </li>
                </ul>
                </div>
            </div>
            </div>
            </div>
        </div>
        <div class="col">
            <div class="row">
                    <div class="col">
                        <h3 class="text-center">Lokalizacja na mapie</h3>
                    </div>
                </div>
                <div class="row">
                    <div class="" id="map"></div>
                </div>
        </div>
    </div>

</section>

<script type="text/javascript">
    loc={{attractionLocalization|safe}}
</script>
{% endblock content %}

{% block scripts %}
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyArdvkTXE1oDlhs3VbJ4KJGYZtclFj79Hg&callback=attractionDetail">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-slimScroll/1.3.8/jquery.slimscroll.min.js"></script>
<script>
        $(function(){
        $('.listing-block').slimScroll({
            height: '800px'
        });
    });
</script>    
{% endblock scripts %}

guide/templates/guide/attraction_filter.html
{% extends "base.html" %}

{% block title %}
    Atrakcje
{% endblock title %}    
{% block styles %}
<style>
.card-columns {
    column-count:3;
}
@media screen and (max-width:992px) {
    .card-columns{
        column-count:3;
    }
}
@media screen and (max-width:768px) {
    .card-columns{
        column-count:2;
    }
}
@media screen and (max-width:600px) {
    .card-columns{
        column-count:1;
    }
}
.card-text{
    position:absolute;
    bottom:20px;
    right:20px;
}
</style>
{% endblock styles %}
{% block attractions_link %}
    <a class="nav-link active" href="{% url 'attractions' %}">Atrakcje</a>
{% endblock attractions_link %}
{% block signin_modal %}
        {% include "registration/signinmodal.html" with redirect='attractions'%}
    {% endblock signin_modal %}
    {% block signup_modal %}
        {% include "registration/signupmodal.html" with redirect='attractions'%}
    {% endblock signup_modal %}
{% block content %}
{% load static %}
{% load widget_tweaks %}
<div class="container-fluid">
<div class="row">
    <div class="col">
        <form action="" method="get" class="form-inline my-3">
                {{ filter.form.categories.label}}
                {{ filter.form.categories|add_class:"form-control ml-2" }}
        </form>
    </div>
    <div class="col text-center my-3">
        <h2>Atrakcje</h2>
    </div>
    <div class="col-4">
</div>
</div>
    <div class="row">
        <div class="col">
            <div class="listing-block"> 
                {% for attraction in filter.qs %}
                {% load my_tags %}
                    {% if forloop.counter0|modulo:3 == 0%}
                        <div class="row mb-5">
                            {% if filter.qs|length < 2 %}
                            <div class="col-6 mx-auto">
                            {% else %}
                            <div class="col">
                            {% endif %}
                                <div class="card-deck w-75 mx-auto">
                    {% endif %}
                    <div class="card w-75 text-left">
                        <img class="card-img-top" src="{% static "images/" %}{{attraction.name}}.jpeg" alt="{{attraction.name}}">
                        <div class="card-body">
                            <h5 class="card-title pb-5">{{attraction.name}}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">
                                <i class="fa fa-clock-o pb-2"></i> {{attraction.getTimeAsFormattedString}} <br>
                                <i class="fa fa-money"></i> {{attraction.getFormattedCost}}
                            </h6>
                            <p class="card-text text-right">
                                <a class="icon-wrapper" href="{% url 'attraction-detail' attraction.pk %}">
                                    <i class="far fa-eye"></i>
                                </a>
                                {% if attraction in availableAttractions %}
                                    <a class="icon-wrapper" href="{% url 'add-attraction-to-shopping-cart' attraction.pk %}">
                                        <i class="fas fa-plus-square"></i>
                                    </a>
                                {% endif %}
                            </p> 
                        </div> 
                    </div>
                    {% if forloop.last %}
                        </div>
                        </div>
                        </div>
                    {% else %}
                        {% if forloop.counter0|modulo:3 == 2%}
                        </div>
                        </div>
                        </div>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block scripts%}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-slimScroll/1.3.8/jquery.slimscroll.min.js"></script>
    <script>
            $(function(){
            $('.listing-block').slimScroll({
                height: '800px'
            });
            $('#id_categories').attr('onchange','this.form.submit()');
        });
    </script>    
{% endblock scripts%}

guide/templates/guide/mytripplan_list.html
{% extends "base.html" %}
{% block title %}
    Attractions
{% endblock title %}  
{% block styles %}
<style>
.card-text{
    position:absolute;
    bottom:20px;
    right:20px;
}
</style>
{% endblock styles %}   
{% block content %}
    {%  load static %}
<div class="container-fluid">
    <div class="row">
        <div class="col text-center">
            <h1 class="display-4 my-2">Twoje plany</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="listing-block"> 
                {% for trip_plan in mytripplans  %}
                    {% if forloop.counter0|divisibleby:2 %}
                        <div class="row mb-5">
                            <div class="col">
                                <div class="row">
                    {% endif %}
                    <div class="col-6">
                    <div class="card w-50 {% cycle 'ml-auto' 'mr-auto' %}">
                        <img class="card-img-top" src="https://www.bialystok.pl/resource/image/192/334/1021/2250/0x0.jpg" alt="{{trip_plan.name}}">
                        <div class="card-body">
                            <h5 class="card-title pb-5">{{trip_plan.name}}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">
                                <i class="fa fa-clock-o pb-2"></i> {{trip_plan.getFormattedTime}} <br>
                                <i class="fa fa-money pb-2"></i> {{trip_plan.getFormattedCost}}<br>
                                <i class="fas fa-map-marker"></i> {{trip_plan.getNumberOfAttractions}}
                            </h6>
                            <p class="card-text text-right">
                                <a class="icon-wrapper" href="{% url 'trip-plan-detail' trip_plan.pk %}">
                                    <i class="far fa-eye"></i>
                                </a>
                                <a class="icon-wrapper" href="{% url 'remove-my-plan' trip_plan.pk %}">
                                    <i class="fas fa-trash-alt"></i>
                                </a>
                            </p> 
                        </div> 
                    </div>
                    </div>
                    {% if not forloop.counter0|divisibleby:2 %}
                    </div>
                    </div>
                    </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block scripts%}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-slimScroll/1.3.8/jquery.slimscroll.min.js"></script>
    <script>
            $(function(){
            $('.listing-block').slimScroll({
                height: '800px'
            });
        });
    </script>    
{% endblock scripts%}

guide/templates/guide/pdf_template.html
<html>
<head>
  <title>PDF</title>
<style>
h3{
    margin-bottom:10px;
    padding:10px 0 10px 0;
    border-bottom:solid 2px blue;
}
h5{
    margin:0;
    color:grey;
}
h4{
    margin:20px 0 10px 0;
}
.attr{
    margin-bottom:25px;
}
.summary{
    margin-top:100px;
}
</style>
</head>

<body>
    <center><h1>{{tripplan.name}}</h1></center>
    <h2>Atrakcje</h2>
    {% for attraction in tripplan.attractions.all %}
    <div class="attr">
        <h3>{{ attraction.name }}</h3>
        <h4>Opis</h4>
        <h5>{{attraction.description}}</h5>
        <h4>Adres</h4>
        <h5>{{attraction.localization}}</h5>
        <h4>Kategoria</h4>
        <h5>{{attraction.display_category}}</h5>
        <h4>Czas i koszt</h4>
        <h5>Czas potrzebny na zwiedzenie: {{ attraction.getTimeAsFormattedString }}</h3>
        <h5>Czas potrzebny na zwiedzenie: {{ attraction.getTimeAsFormattedString }}</h3>
        <h5>Koszy zwiedzenia: {{ attraction.getFormattedCost }}</h3>
    </div>
    {% endfor %}

    <div class="summary">
    <h2>Podsumowanie</h2>
    <h4>Całkowity czas potrzeny na zwiedzanie: {{tripplan.getFormattedTime}}</h4>
    <h4>Całkowity koszt: {{tripplan.getFormattedCost}}</h4>
    </div>

</body>
</html>